### PR TITLE
Flexible aeromap points

### PR DESCRIPTION
**Pull request by codingpoets**
Changes for allowing irregular grid points for the aeroPerformanceMap.

### CODE REVIEW

**Comment by kieh-da** [comment]
Standard multidimensional interpolation routines such as Matlab's _interpn_ only work with uniformly structured ("regular") grid points. Using irregular grid points for aerodynamic (or any other) data would mean a huge additional workload for CPACS users since more advanced interpolation functions would have to be implemented. Is there a plan to supply corresponding interpolation functions? How do you want to aid the users in interpreting the data correctly?

**Comment by CLiersch** [comment]
I think it is a good idea to overcome the limitations of a 4-dimensional, full-factorial grid for aerodynamic data. The current concept produces a significant overhead of unnecessary flight points and unreasonable angles. However, from an aircraft design point of view I think it would be more useful to stick to the concept of polars: There should be a list of arbitrary Mach number and altitude pairs (two vectors with the same index belonging together). For each of these Ma/alt pairs, a range of alpha / beta polars could be given then. Such a concept would also allow for storing an arbitrary list of datapoints, but it would guide the user to thinking in polars, leading to a specific interpolation order (first between angles, then between Ma/alt pairs). It futher should somehow be assured that the delta coefficient points are consistent with the correpsonding points from the base performance map. I do also agree that a documanted interpolation algorithm needs to be provided (best in the form of a software library). Otherwise, everone using this dataset might come to significantly differing Interpolation results).

**Comment by aidan-cfse** [comment]
I think flexible aeromap point will be easier to deal with in a lot of cases. Here's a list of advantage/disadvantage I could think of.

Advantages:
- It is rare you need to calculate the same angles of attack/sideslip for all the flight envelope
- If you need to add just few points of interest, for example to study in more detail cruise regime, those points could be added without changing anything else in the aerodatabase.
- More practical to combine two aerodatabases, for example one for high speed and one for low speed. For those two aerodatabases the angles of attack, sideslip and altitude are generally different, but as only one aeroPerformanceMap is allowed you need to combine them to cover all the flight envelope.
- It is not required to know the correct order of the parameters to find the corresponding coefficient. If parameter vectors have the same length as the coefficients vectors, it is easy to find the corresponding value.

Disadvantage:
- Some change will be required in the way data are read and written.
- Sometime it is practical to use girded data. However, I think it will still be possible to generate and read the points with the same structure and just save them "in line" in the CPACS file.

Other points:
- It would be good to have a kind of description of the aeroPerformanceMap to explain how the coefficients have been generated (physical model, precision,..).

**Comment by MarAlder** [comment]
closed by #589

**Pull request closed without merging**
