### PR TITLE
Added optional confidentiality and clearance nodes to the cpacs header.

### PR DESCRIPTION
**Pull request by codingpoets**

### CODE REVIEW

**Comment by codingpoets** [comment]
closes #508

**Comment by codingpoets** [comment]
I agree. I'll assemble some examples.
Thank you for the feedback.

**Comment by codingpoets** [comment]
So far I did not get a response from the author of the original issue. If there is no response soon, I will remove the issue from the release 3.0 in order not to delay the release any further.

**Comment by MarAlder** [comment]
closed by #508

**Pull request closed without merging**
