### PR TITLE
Change massbreakdown node to complete CERAS structure

### PR DESCRIPTION
**Pull request by AxelBerres**

### CODE REVIEW

**Comment by codingpoets** [comment]
Thank you very much for your contribution. Using a well known structure for the massBreakdown is definetely desirable. I must admit that I am not an expert on how mass breakdowns are used in industry. We will have to get some feedback from other experts on that matter. As far as I know, using CERAS is only one of the possibilities. I am sure you have very good reasons for it, but since I am rather new to this topic, could you explain why you would go for CERAS and not e.g. for ATA chapters?

In order to avoid errors I it would be beneficial to only see the relevant changes which you made to the schema on a particular topic. If you could prepare your commits in a way such that no other changes as e.g. reordering of class definitions are included that would allow for a faster review and integration of your proposal.

Also, since you performed changes concerning different issues, could you create individual pull requests for each of them such that they can be reviewed and accepted individually?

**Comment by AxelBerres** [comment]
It was a decision made during different discussions in the ATLAS Project to choose CERAS instead of ATA for the massBreakDown structure. The description for CERAS massBreakDown is available at http://ceras.ilr.rwth-aachen.de/trac/wiki/CeRAS/Definitions/MassBreakdownDefinition. 
The massBreakDown of CERAS is more aligned to the aircraft design masses and should be therefore prefered.

**Comment by AxelBerres** [comment]
Hallo Jonas,

Ich habe die Begründung ins git eingetragen.

Axel

Von: Jonas Jepsen [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. Juni 2018 15:10
An: DLR-LY/CPACS
Cc: Berres, Axel; Author
Betreff: Re: [DLR-LY/CPACS] Change massbreakdown node to complete CERAS structure (#543)


Thank you very much for your contribution. Using a well known structure for the massBreakdown is definetely desirable. I must admit that I am not an expert on how mass breakdowns are used in industry. We will have to get some feedback from other experts on that matter. As far as I know, using CERAS is only one of the possibilities. I am sure you have very good reasons for it, but since I am rather new to this topic, could you explain why you would go for CERAS and not e.g. for ATA chapters?

In order to avoid errors I it would be beneficial to only see the relevant changes which you made to the schema on a particular topic. If you could prepare your commits in a way such that no other changes as e.g. reordering of class definitions are included that would allow for a faster review and integration of your proposal.

Also, since you performed changes concerning different issues, could you create individual pull requests for each of them such that they can be reviewed and accepted individually?

**Comment by MarAlder** [comment]
topic expired, will be closed

**Pull request closed without merging**
